// src/components/AnimationContainer.tsx
import React, { useState } from 'react';
import { QueryAnimation } from './QueryAnimation';
import { DashboardAnimation } from './DashboardAnimation';
import { TableScanAnimation } from './TableScanAnimation';

export const AnimationContainer: React.FC = () => {
  return (
    <div className="flex flex-wrap justify-center gap-8">
      {/* Data Query Animation */}
      <QueryAnimation onComplete={() => {}} />

      {/* Table Scan Animation */}
      <TableScanAnimation onReset={() => {}} />

      {/* Dashboard Animation */}
      <DashboardAnimation onReset={() => {}} />
    </div>
  );
};

// src/components/AnimationContainer.vue
<template>
  <div class="flex flex-wrap justify-center gap-8">
    <!-- Data Query Animation -->
    <QueryAnimation :on-complete="() => {}" />

    <!-- Table Scan Animation -->
    <TableScanAnimation :on-reset="() => {}" />

    <!-- Dashboard Animation -->
    <DashboardAnimation :on-reset="() => {}" />
  </div>
</template>

<script setup lang="ts">
import QueryAnimation from './QueryAnimation.vue'
import DashboardAnimation from './DashboardAnimation.vue'
import TableScanAnimation from './TableScanAnimation.vue'
</script>
